version: '3.3'

networks:
  squadio-network:

services:  
  api-dev:
    container_name: squadio-dev
    build:
      context: ./src
      dockerfile: ./Dockerfile-Api
    restart: always
    links:
      - rabbit-dev
    ports:
      - 5005:5000
    networks:
      - squadio-network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000/
      - ASPNETCORE_ENVIRONMENT=Development
      #
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      #
      - AppSettings:APISettings:PublicKey=${AppSettings_APISettings_PublicKey}
      - AppSettings:APISettings:ISSUER=${AppSettings_APISettings_ISSUER}
      - AppSettings:APISettings:AUDIENCE=${AppSettings_APISettings_AUDIENCE}
      - AppSettings:APISettings:RefreshTokenExpiresInMinutes=${AppSettings_APISettings_RefreshTokenExpiresInMinutes}
      - AppSettings:APISettings:AccessTokenExpiresInMinutes=${AppSettings_APISettings_AccessTokenExpiresInMinutes}
      - FileTemplateUrl:ImageTemplate=https://squad.api.magora.work/api/files/{Group}/{Resolution}/{Filename}
      - FileTemplateUrl:FileTemplate=https://squad.api.magora.work/api/files/{Group}/{Filename}
      - FileRootDirectory:Path=/var/www/squadio/backend/files
      #
      - GoogleOAuth:ClientId=${GoogleOAuth_ClientId}
      - GoogleOAuth:ClientSecret=${GoogleOAuth_ClientSecret}
      - MicrosoftOAuth:ClientId=e0b221ed-d1ab-42b9-a33d-16410a9572ee
      #
      - RabbitConnection:Host=${RabbitConnection_Host}
      - RabbitConnection:Port=${RabbitConnection_Port}
      - RabbitConnection:Username=${RabbitConnection_Username}
      - RabbitConnection:Password=${RabbitConnection_Password}
    volumes:
      - ../.files:/var/www/squadio/backend/files
  
  email-sender-dev:
    container_name: squadio-email-sender-dev
    build:
      context: ./src
      dockerfile: ./Dockerfile-EmailSender
    restart: always
    links:
      - rabbit-dev
    networks:
      - squadio-network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000/
      - ASPNETCORE_ENVIRONMENT=Development
      #
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      #
      - StaticUrls:SetPasswordUrl=https://squad.magora.work/sign-up/set-password
      - StaticUrls:ResetPasswordUrl=https://squad.magora.work/auth/set-password
      - StaticUrls:ResetPasswordAdminUrl=https://squad.web.magora.work/auth/set-password
      - StaticUrls:InviteToCompanyPageUrl=https://squad.magora.work/company/invite
      - StaticUrls:InviteToTeamPageUrl=https://squad.magora.work/team/invite
      - StaticUrls:InviteToProjectPageUrl=https://squad.magora.work/project/invite
      #
      - EmailSettings:SmtpServer=${EmailSettings_SmtpServer}
      - EmailSettings:SmtpPort=${EmailSettings_SmtpPort}
      - EmailSettings:Name=${EmailSettings_Name}
      - EmailSettings:Email=${EmailSettings_Email}
      - EmailSettings:Password=${EmailSettings_Password}
      #
      - RabbitConnection:Host=${RabbitConnection_Host}
      - RabbitConnection:Port=${RabbitConnection_Port}
      - RabbitConnection:Username=${RabbitConnection_Username}
      - RabbitConnection:Password=${RabbitConnection_Password}

  rabbit-dev:
    image: "rabbitmq:3-management"
    hostname: "rabbit-dev"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: ${RabbitConnection_Username}
      RABBITMQ_DEFAULT_PASS: ${RabbitConnection_Password}
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - squadio-network
    ports:
      - "15672:15672"
      - "5672:5672"