version: '3.3'

networks:
  squadio-network:

services:
  sql-dev:
    image: postgres:10.4
    container_name: squadio-sql-dev
    hostname: sql-dev
    restart: always
    ports:
      - 15432:5432
    networks:
      - squadio-network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - /var/db/data-dev/postgresql:/var/lib/postgresql