version: '3.3'

networks:
  squadio-network:

services:  
  api-dev:
    container_name: squadio-api-dev
    build:
      context: ./src
      dockerfile: ./Dockerfile-Api
    restart: always
    ports:
      - 5005:5000
    networks:
      - squadio-network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000/
      - ASPNETCORE_ENVIRONMENT=Stage
      #
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../.files:/var/www/squadio/backend/files