version: '3.3'

networks:
  squadio-network:

services:
  sql-dev:
    image: postgres:10.4
    container_name: squadio-sql-dev
    hostname: sql-dev
    restart: always
    ports:
      - 15432:5432
    networks:
      - squadio-network
    environment:
      - POSTGRES_USER=user_dev
      - POSTGRES_PASSWORD=135642QWSX
      - POSTGRES_DB=squadio_dev
      - POSTGRES_HOST=sql-dev
    volumes:
      - /var/db/data-dev/postgresql:/var/lib/postgresql
  
  api-dev:
    container_name: squadio-dev
    build:
      context: ./src
      dockerfile: ./Dockerfile-Api
    restart: always
    links:
      - sql-dev
      - rabbit-dev
    ports:
      - 5005:5000
    networks:
      - squadio-network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000/
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=sql-dev
      - DB_PORT=5432
      - DB_NAME=squadio_dev
      - DB_USER=user_dev
      - DB_PASSWORD=135642QWSX
      - AppSettings:APISettings:PublicKey=AAAAB3NzaC1yc2EAAAADAQABAAABAQCkkTqYqjfy11DUtK6rhiQutHiBnQgNVq
      - AppSettings:APISettings:ISSUER=Squad
      - AppSettings:APISettings:AUDIENCE=IO
      - AppSettings:APISettings:RefreshTokenExpiresInMinutes=10080
      - AppSettings:APISettings:AccessTokenExpiresInMinutes=1440
      - GoogleOAuth:ClientId=63806648351-k2ebqg66tab5760qa4i3mmomfslbmuvd.apps.googleusercontent.com
      - GoogleOAuth:ClientSecret=yY2sMMKF-a3JRheGcMMOSFpx
      - MicrosoftOAuth:ClientId=e0b221ed-d1ab-42b9-a33d-16410a9572ee
      - StaticUrls:SetPasswordUrl=https://squad.magora.work/sign-up/set-password
      - StaticUrls:ResetPasswordUrl=https://squad.magora.work/auth/set-password
      - StaticUrls:InviteToTeamPageUrl=https://squad.magora.work/team/invite
      - StaticUrls:InviteToProjectPageUrl=https://squad.magora.work/project/invite
  
  email-sender-dev:
    container_name: squadio-email-sender-dev
    build:
      context: ./src
      dockerfile: ./Dockerfile-EmailSender
    restart: always
    links:
      - rabbit-dev
    ports:
      - 5006:5000
    networks:
      - squadio-network

  rabbit-dev:
    image: "rabbitmq:3-management"
    hostname: "rabbit-dev"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - squadio-network
    ports:
      - "15672:15672"
      - "5672:5672"
 
volumes:
  rabbit:
    driver: local